togglz:
  # noinspection SpringBootApplicationYaml
  enabled: ${config.togglz.enabled}
  table:
    name: FeatureToggles
  caching:
    state.repository.ttl: 10000
  console:
    enabled: true
    secured: false
    path: /actuator/togglz
    use-management-port: false
  features:
    # Use comma separated list of group names for the 'groups' field
    WEB_SECURITY:
      enabled: false
      label: Enable/disable Web Security
      groups: Config
    CONTROLLER_EXECUTION:
      enabled: true
      label: Make Controller executable
      groups: Sample
    METHOD_EXECUTION:
      enabled: true
      label: Make Method executable
      groups: Sample
    CONDITIONAL_STATEMENTS_EXECUTION:
      enabled: true
      label: Make Statement executable
      groups: Sample
    MAKE_COFFEE:
      enabled: true
      label: Making a cup of coffee
      groups: Sample, Brewing
    MAKE_TEA:
      enabled: true
      label: Making a cup of tea
      groups: Brewing