package pk.lucidxpo.ynami.spring.security.helper;

public enum EndPointTestScenario {
    SECURITY_DISABLED_AUTHENTICATED_WITHOUT_CSRF,
    SECURITY_DISABLED_AUTHENTICATED_WITH_VALID_CSRF,
    SECURITY_DISABLED_AUTHENTICATED_WITH_INVALID_CSRF,
    SECURITY_DISABLED_UNAUTHENTICATED_WITHOUT_CSRF,
    SECURITY_DISABLED_UNAUTHENTICATED_WITH_VALID_CSRF,
    SECURITY_DISABLED_UNAUTHENTICATED_WITH_INVALID_CSRF,
    SECURITY_ENABLED_AUTHENTICATED_WITHOUT_CSRF,
    SECURITY_ENABLED_AUTHENTICATED_WITH_VALID_CSRF,
    SECURITY_ENABLED_AUTHENTICATED_WITH_INVALID_CSRF,
    SECURITY_ENABLED_UNAUTHENTICATED_WITHOUT_CSRF,
    SECURITY_ENABLED_UNAUTHENTICATED_WITH_VALID_CSRF,
    SECURITY_ENABLED_UNAUTHENTICATED_WITH_INVALID_CSRF
}