-- Used by Hibernate
CREATE TABLE IF NOT EXISTS `hibernate_sequence` (
  `next_val` bigint(20) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=UTF8MB4;

INSERT INTO hibernate_sequence (next_val) VALUES (0);

-- Used by Togglz
CREATE TABLE IF NOT EXISTS `FeatureToggles` (
  `FEATURE_NAME` VARCHAR(100) NOT NULL,
  `FEATURE_ENABLED` INTEGER DEFAULT NULL,
  `STRATEGY_ID` VARCHAR(200) DEFAULT NULL,
  `STRATEGY_PARAMS` VARCHAR(2000) DEFAULT NULL,
  PRIMARY KEY (`FEATURE_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=UTF8MB4;