name: 'YNaMi CI/CD'
on: push
env:
  JAVA_VERSION: 20
  MYSQL_VERSION: 8.0
  UPLOADED_ARTIFACTS_DIR: 'gh-pages'

jobs:
#  setup-mysql:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: shogo82148/actions-setup-mysql@v1
#        with:
#          mysql-version: "8.0"
#          root-password: "root"
#      - run: mysql -uroot -proot -e 'SELECT version()'


  laravel_tests:
    runs-on: ubuntu-latest
    env:
      DB_PORT: 3306
      DB_HOST: localhost
      DB_CONNECTION: mysql
    steps:
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - run: mysql -uroot -proot -e 'SELECT version()'

      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2


      - name: 'Resolve Maven dependencies'
        run: mvn dependency:resolve --file pom.xml
      - name: 'Run the db migration tests'
        run: mvn -Djacoco.haltOnFailure=false clean test -P mt --file pom.xml

