name: 'YNaMi CI/CD'
on: push
env:
  JAVA_VERSION: 20
  MYSQL_VERSION: 8.0
  CHROMIUM_VERSION: 116.0.5845.140-1
  UPLOADED_ARTIFACTS_DIR: 'gh-pages'
  UNIT_TESTS_XMLS_DIR: 'target/test-results/unit-tests/*.xml'
  INTEGRATION_TESTS_XMLS_DIR: 'target/test-results/integration-tests/*.xml'

jobs:
#  bdd-cucumber-tests-without-install:
#    runs-on: ubuntu-22.04
#
#
## With Selenium 4.11
## Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
## - Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
## Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
## - Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
## Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
## - Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
## Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
## - Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
## Unable to find an exact match for CDP version 116, so returning the closest version found: 115
## - Unable to find an exact match for CDP version 116, so returning the closest version found: 115
#
#
#
#
## With Selenium 4.12
## without .driverVersion(CHROME_VERSION).browserVersion(CHROME_VERSION)
## Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
## Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
## Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null
#
#
#
## with .driverVersion(CHROME_VERSION).browserVersion(CHROME_VERSION)
## This version of ChromeDriver only supports Chrome version 114
## 404 for chrome-for-testing/116/linux64/chromedriver-linux64.zip
## Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver
## Using chromedriver 114.0.5735.90 (resolved driver for Chrome 116)
## This version of ChromeDriver only supports Chrome version 114
## Current browser version is 116.0.5845.96 with binary path /usr/bin/google-chrome
#    steps:
#      - name: 'Get the latest code from the `${{ github.repository }}` repository'
#        uses: actions/checkout@v3
#      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
#        uses: './.github/actions/install-java'
#        with:
#          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
#      - name: 'Set up MySQL'
#        run: sudo systemctl start mysql
#      - name: 'MySQL Version'
#        run: mysql --version
#      - name: 'Google Chrome Version'
## This has printed 'Google Chrome 116.0.5845.96'
#        run: |
#          google-chrome --version
##          "CHROME_BIN" --version ; "$CHROMEWEBDRIVER/chromedriver --version"
#      - name: 'Run the acceptance-cucumber tests'
#        run: browser=chrome headless_mode=true mvn clean test -P bt,mysql --file pom.xml
#
#  bdd-cucumber-tests-with-install:
#    runs-on: ubuntu-22.04
#
#
## Same results with Selenium 4.11 and 4.12
## without .driverVersion(CHROME_VERSION).browserVersion(CHROME_VERSION)
## Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver
## Using chromedriver 116.0.5845.96 (resolved driver for Chrome 116)
## Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null
#
#
#
#
## with .driverVersion(CHROME_VERSION).browserVersion(CHROME_VERSION)
## This version of ChromeDriver only supports Chrome version 114
## 404 for chrome-for-testing/116/linux64/chromedriver-linux64.zip
## Exporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver
## Using chromedriver 114.0.5735.90 (resolved driver for Chrome 116)
## Current browser version is 116.0.5845.140 with binary path /usr/bin/google-chrome
#    steps:
#      - name: 'Get the latest code from the `${{ github.repository }}` repository'
#        uses: actions/checkout@v3
#      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
#        uses: './.github/actions/install-java'
#        with:
#          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
#      - name: 'Set up MySQL'
#        run: sudo systemctl start mysql
#      - name: 'MySQL Version'
#        run: mysql --version
#
#      - name: 'Install Google Chrome'
#        run: |
#          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.140-1_amd64.deb
#          sudo apt install -y ./google-chrome-stable_116.0.5845.140-1_amd64.deb
#      - name: 'Google Chrome Version'
## This has printed 'Google Chrome 116.0.5845.140'
#        run: |
#          google-chrome --version
##          "CHROME_BIN" --version ; "$CHROMEWEBDRIVER/chromedriver --version"
#      - name: 'Update Google Chrome version'
#        run: update-alternatives --skip-auto --config google-chrome
#      - name: 'Run the acceptance-cucumber tests'
#        run: browser=chrome headless_mode=true mvn clean test -P bt,mysql --file pom.xml

  chrome-version-without-install:
    runs-on: ubuntu-22.04

    steps:
      - name: 'Google Chrome Version'
# This has printed 'Google Chrome 116.0.5845.96'
        run: |
          google-chrome --version
#          "CHROME_BIN" --version ; "$CHROMEWEBDRIVER/chromedriver --version"

  webdriver-without-install:
    runs-on: ubuntu-22.04

    steps:
      - name: 'Which chromedriver'
#        /usr/bin/chromedriver
        run: which chromedriver


#  webdriver-run-without-install:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: 'chromedriver run'
##        Starting ChromeDriver 116.0.5845.96
##        ChromeDriver was started successfully.
#        run: chromedriver

#  webdriver-run-full-path-without-install:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: 'chromedriver run'
##        not found
#        run: /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.96/chromedriver


#  webdriver-run-with-install:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: 'Install Google Chrome'
#        run: |
#          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.140-1_amd64.deb
#          sudo apt install -y ./google-chrome-stable_116.0.5845.140-1_amd64.deb
#      - name: 'chromedriver run'
#        #        Starting ChromeDriver 116.0.5845.96
#        #        ChromeDriver was started successfully.
#        run: chromedriver



#  webdriver-run-full-path-with-install:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: 'Install Google Chrome'
#        run: |
#          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.140-1_amd64.deb
#          sudo apt install -y ./google-chrome-stable_116.0.5845.140-1_amd64.deb
#      - name: 'chromedriver run'
##        not found
#        run: /home/runner/.cache/selenium/chromedriver/linux64/116.0.5845.140/chromedriver

  webdriver-install:
    runs-on: ubuntu-22.04

    steps:
      - name: Unit test
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -qqy
          sudo apt-get -qqy install google-chrome-stable
          CHROME_VERSION=$(google-chrome-stable --version)
          CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
          CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
          sudo rm /etc/apt/sources.list.d/google-chrome.list
          echo ${CHROME_VERSION}
          echo ${CHROME_FULL_VERSION}
          echo ${CHROME_MAJOR_VERSION}
          export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
          echo ${CHROMEDRIVER_VERSION}
          curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
          chromedriver --version
          which chromedriver
          which google-chrome



# install the latest version => working and installs 116
#      - name:  Install Google Chrome # Using shell commands to install Google Chrome
#        run: |
#          set -ex
#          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#          sudo apt install ./google-chrome-stable_current_amd64.deb
#      - name: 'Google Chrome Version'
#        run: google-chrome --version


#
#      - name: Install Google Chrome # Using shell commands to install Google Chrome
#        run: |
#          wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.140-1_amd64.deb \ && sudo apt install -y /tmp/chrome.deb \ && sudo rm /tmp/chrome.deb
#          cd /tmp/
#          sudo dpkg -i chrome.deb
#      - name: 'Google Chrome Version'
#        run: google-chrome --version