name: 'YNaMi CI/CD'
on: push
env:
  JAVA_VERSION: 20
  MYSQL_VERSION: 8.0
  CHROMIUM_VERSION: 116.0.5845.140-1
  UPLOADED_ARTIFACTS_DIR: 'gh-pages'
  UNIT_TESTS_XMLS_DIR: 'target/test-results/unit-tests/*.xml'
  INTEGRATION_TESTS_XMLS_DIR: 'target/test-results/integration-tests/*.xml'

jobs:
  bdd-cucumber-tests-without-install:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Set up MySQL'
        run: sudo systemctl start mysql
      - name: 'MySQL Version'
        run: mysql --version


# install the latest version => working and installs 116
#      - name:  Install Google Chrome # Using shell commands to install Google Chrome
#        run: |
#          set -ex
#          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#          sudo apt install ./google-chrome-stable_current_amd64.deb
#      - name: 'Google Chrome Version'
#        run: google-chrome --version


#
#      - name: Install Google Chrome # Using shell commands to install Google Chrome
#        run: |
#          wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.140-1_amd64.deb \ && sudo apt install -y /tmp/chrome.deb \ && sudo rm /tmp/chrome.deb
#          cd /tmp/
#          sudo dpkg -i chrome.deb
#      - name: 'Google Chrome Version'
#        run: google-chrome --version
#
      - name: 'Run the acceptance-cucumber tests'
        run: browser=chrome headless_mode=true mvn clean test -P bt,mysql --file pom.xml

  bdd-cucumber-tests-with-install:
    runs-on: ubuntu-latest

    steps:
      - name: 'Get the latest code from the `${{ github.repository }}` repository'
        uses: actions/checkout@v3
      - name: 'Set up the Oracle JDK `${{ env.JAVA_VERSION }}`'
        uses: './.github/actions/install-java'
        with:
          JAVA_VERSION_TO_INSTALL: ${{ env.JAVA_VERSION }}
      - name: 'Set up MySQL'
        run: sudo systemctl start mysql
      - name: 'MySQL Version'
        run: mysql --version

      - name: 'Install Google Chrome'
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_116.0.5845.140-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_116.0.5845.140-1_amd64.deb
      - name: 'Google Chrome Version'
        run: google-chrome --version
      - name: 'Run the acceptance-cucumber tests'
        run: browser=chrome headless_mode=true mvn clean test -P bt,mysql --file pom.xml

  chrome-version-without-install:
    runs-on: ubuntu-latest

    steps:
      - name: 'Google Chrome Version'
        run: google-chrome --version

  webdriver-without-install:
    runs-on: ubuntu-latest

    steps:
      - name: 'Which WebDriver'
        run: which webdriver